# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('DONE', 'Done')], max_length=35, verbose_name='Status')),
                ('schedule', models.DateTimeField(verbose_name='Schedule')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
