# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('DONE', 'Done')], max_length=35, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.TextField(verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
